language: node_js

node_js:
  - "stable"

cache:
  directories:
  - node_modules

deploy:
  privider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master

before_script:
  - "npm i -g gatsby-cli"
  - "yarn"

script:
  - yarn deploy